include:
    # Metadata shared by many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml

    # OS builds
    - local: .gitlab/os-ios.yml

stages:
    - Test SDK
    - Build Sample
    - Publish To AppStore # Only for TestFlight testing

############################################## pipeline jobs

testSDK:release:
  extends:
    - .conf:env
    - .conf:release
    - .conf:runner:tags
    - .conf:rule:default
    - .testSDK:do

buildSample:debug:
  extends:
    - .conf:env
    - .conf:debug
    - .conf:artifacts
    - .conf:runner:tags
    - .conf:rule:default
    - .buildSample:do

publishToAppStore:release:
  extends:
    - .conf:env
    - .conf:release
    - .conf:runner:tags
    - .conf:rule:defaultBranch
    - .publishToAppStore:do